apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsa-fe
  namespace: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: fsa-fe
  template:
    metadata:
      labels:
        app: fsa-fe
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: fsa-fe
          image: acrfsapoiasniko.azurecr.io/rental-frontend:latest
          imagePullPolicy: Always
          resources:
            # TODO: nastavit podla metrik podu, toto su len odhadnute hodnoty
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 150m
              memory: 150Mi
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
            httpGet:
              path: /
              port: http

        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:1.3
          args:
            - --nginx.scrape-uri=http://127.0.0.1/nginx_status
          ports:
            - name: metrics
              containerPort: 9113
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 16Mi
